### PR TITLE
Python3 update

### PR DESCRIPTION
**Pull request by mjessome**
Let's get with the times and update to python3!

### CODE REVIEW

**Comment by sarfata** [comment]
image

**Comment by sarfata** [comment]
👍 of course ;) thx @mjessome !

**Comment by HBehrens** [comment]
I was about to say that I would love to have CI but it seems that we do! (it's been a while, sorry folks)
@mjessome do you think you can update the `.travis.yml` accordingly?
@sarfata do you think we should rather switch to gh-actions for this? If so, would we simply remove `.travis.yml` in this PR and do that transition in a follow-up PR?

**Comment by sarfata** [comment]
Unfortunately CI has been broken for a while - see #25 - I failed and failed to pick it up ...

So yes I think removing travis is a great way to move this PR forward 😜

**Comment by mjessome** [comment]
Thanks for looking, guys!

> I was about to say that I would love to have CI but it seems that we do! (it's been a while, sorry folks)
> @mjessome do you think you can update the `.travis.yml` accordingly?

I bumped travis python version to 3.7 and disabled the failing PlatformIO tests. At least the nosetests seem to still work and have value 😄

**Comment by HBehrens** [comment]
Did a quick manual smoke test locally and this LGTM :) also filed two follow-up tasks.

Thank you @mjessome !

**Pull request merged**
